namespace :rename_regions do
  desc "rename regions"
  task default: :environment do
    country_region = [
      {id: 2,  region: "Latin America and the Caribbean"},
      {id: 3,  region: "India, Central and West Asia"},
      {id: 4,  region: "India, Central and West Asia"},
      {id: 5,  region: "Mediterranean Rim"},
      {id: 6,  region: "India, Central and West Asia"},
      {id: 7,  region: "Sub-Saharan Africa"},
      {id: 8,  region: "Latin America and the Caribbean"},
      {id: 9,  region: "developed country"},
      {id: 10, region: "developed country"},
      {id: 11, region: "India, Central and West Asia"},
      {id: 12, region: "Mediterranean Rim"},
      {id: 13, region: "India, Central and West Asia"},
      {id: 14, region: "India, Central and West Asia"},
      {id: 15, region: "developed country"},
      {id: 16, region: "Sub-Saharan Africa"},
      {id: 17, region: "developed country"},
      {id: 18, region: "India, Central and West Asia"},
      {id: 19, region: "Sub-Saharan Africa"},
      {id: 20, region: "Sub-Saharan Africa"},
      {id: 21, region: "South and East Asia"},
      {id: 22, region: "Latin America and the Caribbean"},
      {id: 23, region: "Latin America and the Caribbean"},
      {id: 24, region: "South and East Asia"},
      {id: 25, region: "Sub-Saharan Africa"},
      {id: 26, region: "developed country"},
      {id: 27, region: "developed country"},
      {id: 28, region: "Sub-Saharan Africa"},
      {id: 29, region: "Sub-Saharan Africa"},
      {id: 30, region: "Sub-Saharan Africa"},
      {id: 31, region: "developed country"},
      {id: 32, region: "Sub-Saharan Africa"},
      {id: 33, region: "Latin America and the Caribbean"},
      {id: 34, region: "Sub-Saharan Africa"},
      {id: 35, region: "South and East Asia"},
      {id: 36, region: "Latin America and the Caribbean"},
      {id: 37, region: "Latin America and the Caribbean"},
      {id: 38, region: "Latin America and the Caribbean"},
      {id: 39, region: "Sub-Saharan Africa"},
      {id: 40, region: "developed country"},
      {id: 41, region: "developed country"},
      {id: 42, region: "developed country"},
      {id: 43, region: "developed country"},
      {id: 44, region: "Latin America and the Caribbean"},
      {id: 45, region: "Mediterranean Rim"},
      {id: 46, region: "Latin America and the Caribbean"},
      {id: 47, region: "developed country"},
      {id: 48, region: "Mediterranean Rim"},
      {id: 49, region: "developed country"},
      {id: 50, region: "Sub-Saharan Africa"},
      {id: 51, region: "developed country"},
      {id: 52, region: "developed country"},
      {id: 53, region: "Sub-Saharan Africa"},
      {id: 54, region: "developed country"},
      {id: 55, region: "India, Central and West Asia"},
      {id: 56, region: "developed country"},
      {id: 57, region: "Sub-Saharan Africa"},
      {id: 58, region: "Sub-Saharan Africa"},
      {id: 59, region: "developed country"},
      {id: 60, region: "Latin America and the Caribbean"},
      {id: 61, region: "developed country"},
      {id: 62, region: "Latin America and the Caribbean"},
      {id: 63, region: "Sub-Saharan Africa"},
      {id: 64, region: "developed country"},
      {id: 65, region: "South and East Asia"},
      {id: 66, region: "Latin America and the Caribbean"},
      {id: 67, region: "developed country"},
      {id: 68, region: "Latin America and the Caribbean"},
      {id: 69, region: "developed country"},
      {id: 70, region: "South and East Asia"},
      {id: 71, region: "developed country"},
      {id: 72, region: "developed country"},
      {id: 73, region: "India, Central and West Asia"},
      {id: 74, region: "India, Central and West Asia"},
      {id: 75, region: "India, Central and West Asia"},
      {id: 76, region: "developed country"},
      {id: 77, region: "developed country"},
      {id: 78, region: "Latin America and the Caribbean"},
      {id: 79, region: "India, Central and West Asia"},
      {id: 80, region: "developed country"},
      {id: 81, region: "Sub-Saharan Africa"},
      {id: 82, region: "India, Central and West Asia"},
      {id: 83, region: "South and East Asia"},
      {id: 84, region: "Sub-Saharan Africa"},
      {id: 85, region: "South and East Asia"},
      {id: 86, region: "South and East Asia"},
      {id: 87, region: "India, Central and West Asia"},
      {id: 88, region: "India, Central and West Asia"},
      {id: 89, region: "South and East Asia"},
      {id: 90, region: "Mediterranean Rim"},
      {id: 91, region: "India, Central and West Asia"},
      {id: 92, region: "Sub-Saharan Africa"},
      {id: 93, region: "Sub-Saharan Africa"},
      {id: 94, region: "developed country"},
      {id: 95, region: "developed country"},
      {id: 96, region: "developed country"},
      {id: 97, region: "Mediterranean Rim"},
      {id: 98, region: "Mediterranean Rim"},
      {id: 99, region: "developed country"},
      {id: 100,region: "Sub-Saharan Africa"},
      {id: 101,region: "developed country"},
      {id: 102,region: "Sub-Saharan Africa"},
      {id: 103,region: "South and East Asia"},
      {id: 104,region: "South and East Asia"},
      {id: 105,region: "developed country"},
      {id: 106,region: "Sub-Saharan Africa"},
      {id: 107,region: "developed country"},
      {id: 108,region: "Sub-Saharan Africa"},
      {id: 109,region: "Sub-Saharan Africa"},
      {id: 110,region: "Latin America and the Caribbean"},
      {id: 111,region: "South and East Asia"},
      {id: 112,region: "Sub-Saharan Africa"},
      {id: 113,region: "Sub-Saharan Africa"},
      {id: 114,region: "Sub-Saharan Africa"},
      {id: 115,region: "Sub-Saharan Africa"},
      {id: 116,region: "Latin America and the Caribbean"},
      {id: 117,region: "developed country"},
      {id: 118,region: "developed country"},
      {id: 119,region: "India, Central and West Asia"},
      {id: 120,region: "developed country"},
      {id: 121,region: "India, Central and West Asia"},
      {id: 122,region: "Latin America and the Caribbean"},
      {id: 123,region: "Latin America and the Caribbean"},
      {id: 124,region: "developed country"},
      {id: 125,region: "Z"},
      {id: 126,region: "South and East Asia"},
      {id: 127,region: "India, Central and West Asia"},
      {id: 128,region: "developed country"},
      {id: 129,region: "Latin America and the Caribbean"},
      {id: 130,region: "India, Central and West Asia"},
      {id: 131,region: "developed country"},
      {id: 132,region: "Latin America and the Caribbean"},
      {id: 133,region: "India, Central and West Asia"},
      {id: 134,region: "developed country"},
      {id: 135,region: "developed country"},
      {id: 136,region: "developed country"},
      {id: 137,region: "developed country"},
      {id: 138,region: "Sub-Saharan Africa"},
      {id: 139,region: "India, Central and West Asia"},
      {id: 140,region: "South and East Asia"},
      {id: 141,region: "Sub-Saharan Africa"},
      {id: 142,region: "developed country"},
      {id: 143,region: "developed country"},
      {id: 144,region: "developed country"},
      {id: 145,region: "developed country"},
      {id: 146,region: "Sub-Saharan Africa"},
      {id: 147,region: "Sub-Saharan Africa"},
      {id: 148,region: "Sub-Saharan Africa"},
      {id: 149,region: "Latin America and the Caribbean"},
      {id: 150,region: "Latin America and the Caribbean"},
      {id: 151,region: "India, Central and West Asia"},
      {id: 152,region: "Sub-Saharan Africa"},
      {id: 153,region: "Sub-Saharan Africa"},
      {id: 154,region: "Sub-Saharan Africa"},
      {id: 155,region: "South and East Asia"},
      {id: 156,region: "India, Central and West Asia"},
      {id: 157,region: "Mediterranean Rim"},
      {id: 158,region: "Mediterranean Rim"},
      {id: 159,region: "Latin America and the Caribbean"},
      {id: 160,region: "developed country"},
      {id: 161,region: "Sub-Saharan Africa"},
      {id: 162,region: "developed country"},
      {id: 163,region: "Sub-Saharan Africa"},
      {id: 164,region: "developed country"},
      {id: 165,region: "Latin America and the Caribbean"},
      {id: 166,region: "India, Central and West Asia"},
      {id: 167,region: "Latin America and the Caribbean"},
      {id: 168,region: "South and East Asia"},
      {id: 169,region: "India, Central and West Asia"},
      {id: 170,region: "Sub-Saharan Africa"},
      {id: 171,region: "Sub-Saharan Africa"},
      {id: 172,region: "Sub-Saharan Africa"},
    ]
    country_region.each {|cr| Country.find(cr[:id]).update(region: cr[:region])}
#    Presentation.all.map {|presentation| presentation.update(:pre_proposal_date => DateTime.current)}
  end
end
