development:
  adapter: mysql2
  encoding: utf8
  database: cimpa_development
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: cimpa_test
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  database: cimpa_production
  username: root
  password: 
